name: temp_datascience
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=2.0.0
  - aiofiles=22.1.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - aiosqlite=0.19.0
  - alabaster=0.7.12
  - albumentations=1.3.1
  - anaconda-client=1.11.2
  - anaconda-navigator=2.4.0
  - anaconda-project=0.11.1
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - astroid=2.14.2
  - astropy=5.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - automat=20.2.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bayesian-optimization=1.4.3
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.6.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.3
  - blosc=1.21.3
  - bokeh=2.4.3
  - boltons=23.0.0
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0002
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cachetools=5.3.1
  - cairo=1.16.0
  - catboost=1.2.2
  - certifi=2023.11.17
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0003
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.2
  - conda=23.3.1
  - conda-build=3.24.0
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - conda-repo-cli=1.0.41
  - conda-token=0.4.0
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - constantly=15.1.0
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=39.0.1
  - cssselect=1.1.0
  - cuda-cccl=12.3.101
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.3.101
  - cuda-runtime=11.8.0
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - daal4py=2023.0.2
  - dal=2023.0.1
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - datashader=0.14.4
  - datashape=0.5.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - distributed=2022.7.0
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - eigen=3.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.5.0
  - ffmpeg=4.2.3
  - filelock=3.9.0
  - flake8=6.0.0
  - flask=2.2.2
  - flatbuffers=2.0.0
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - future=0.18.3
  - gast=0.4.0
  - gensim=4.3.0
  - getopt-win32=0.1
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - google-auth=2.23.2
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - greenlet=2.0.1
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gts=0.7.6
  - h5py=3.7.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - holoviews=1.15.4
  - huggingface_hub=0.10.1
  - hvplot=0.8.2
  - hyperlink=21.0.0
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imagehash=4.3.1
  - imageio=2.26.0
  - imagesize=1.4.1
  - imbalanced-learn=0.10.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - incremental=21.3.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.7
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - joblib=1.1.1
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.6.2
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kaggle=1.5.16
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - keyring=23.4.0
  - kiwisolver=1.4.4
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcurl=7.87.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libiconv=1.16
  - libjpeg-turbo=2.1.3
  - liblief=0.12.3
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - lightgbm=4.1.0
  - llvmlite=0.39.1
  - locket=1.0.0
  - lxml=4.9.1
  - lz4=3.1.3
  - lz4-c=1.9.4
  - lzo=2.10
  - m2-msys2-runtime
  - m2-patch=2.7.5
  - m2w64-libwinpthread-git
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - menuinst=1.4.19
  - mistune=0.8.4000
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - mpmath=1.2.1
  - msgpack-python=1.0.3
  - msys2-conda-epoch=20160418
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - navigator-updater=0.3.0
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.7
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - numpydoc=1.5.0
  - oauthlib=3.2.2
  - opencv=4.6.0
  - opencv-python-headless=4.8.1.78
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=22.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - panel=0.14.3
  - pango=1.50.7
  - param=1.12.3
  - paramiko=2.8.1
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - pathlib=1.0.1
  - pathspec=0.10.3
  - patsy=0.5.3
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5003
  - pillow=9.4.0
  - pip=22.3.1
  - pixman=0.40.0
  - pkginfo=1.9.6
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - poppler=22.12.0
  - poppler-data=0.4.12
  - powershell_shortcut=0.0.1
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protego=0.1.16
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-lief=0.12.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.1
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.0
  - pyflakes=3.0.1
  - pygments=2.11.2
  - pyhamcrest=2.0.2
  - pyjwt=2.4.0
  - pylint=2.16.2
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyodbc=4.0.34
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.1.2
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=23.5.26
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-libarchive-c=2.9
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.1
  - python-slugify=5.0.2
  - python-snappy=0.6.1
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyu2f=0.1.5
  - pyviz_comms=2.0.2
  - pywavelets=1.4.1
  - pywin32=305
  - pywin32-ctypes=0.2.0000
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtpy=2.2.0
  - qtwebkit=5.212
  - qudida=0.0.4
  - queuelib=1.5.0
  - regex=2022.7.9
  - requests=2.31.0
  - requests-file=1.5.1
  - requests-oauthlib=1.3.1
  - requests-toolbelt=0.9.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rope=1.7.0
  - rsa=4.9
  - rtree=1.0.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.17.21
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scikit-learn-intelex=2023.0.2
  - scipy=1.10.0
  - scrapy=2.8.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - service_identity=18.1.0
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.1
  - spyder-kernels=2.4.1
  - sqlalchemy=1.4.39
  - sqlite=3.40.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tabulate=0.8.10
  - tangled-up-in-unicode=0.2.0
  - tbb=2021.7.0
  - tbb4py=2021.7.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.3.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - tldextract=3.2.0
  - tokenizers=0.11.4
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.7.1
  - transformers=4.24.0
  - twisted=22.2.0
  - twisted-iocpsupport=1.0.2
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2022g
  - ujson=5.4.0
  - unidecode=1.2.0
  - urllib3=1.26.14
  - vc=14.2
  - visions=0.7.5
  - vs2015_runtime=14.27.29016
  - w3lib=1.21.0
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.2
  - whatthepatch=1.0.2
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wordcloud=1.9.2
  - wrapt=1.14.1
  - xarray=2022.11.0
  - xlwings=0.29.1
  - xz=5.2.10
  - y-py=0.5.9
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.7.2
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.1.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zope=1.0
  - zope.interface=5.4.0
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - click-plugins==1.1.1
      - cligj==0.7.2
      - dacite==1.8.1
      - descartes==1.1.0
      - fiona==1.9.4.post1
      - geopandas==0.13.2
      - htmlmin==0.1.12
      - multimethod==1.9.1
      - pandas-profiling==3.6.6
      - phik==0.12.3
      - pydantic==1.10.12
      - pylint-venv==2.3.0
      - pyproj==3.6.0
      - qstylizer==0.2.2
      - qtawesome==1.2.2
      - qtconsole==5.4.0
      - shapely==2.0.1
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - typeguard==2.13.3
      - ydata-profiling==4.5.1
